name: Trigger auto deployment for container-app-kls3rdcpfbp4a

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-kls3rdcpfbp4a-AutoDeployTrigger-3aec0253-d2f7-42b3-bd4c-7d65dcd517f5.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPKLS3RDCPFBP4A_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPKLS3RDCPFBP4A_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPKLS3RDCPFBP4A_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistrykls3rdcpfbp4a.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPKLS3RDCPFBP4A_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPKLS3RDCPFBP4A_REGISTRY_PASSWORD }}
          containerAppName: container-app-kls3rdcpfbp4a
          resourceGroup: expresssampleb4e56a0f9
          imageToBuild: containerregistrykls3rdcpfbp4a.azurecr.io/container-app-kls3rdcpfbp4a:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


